### ISSUE TITLE
Can't start openvpn

### ISSUE THREAD

**Issue by Christoph-AK** [Archef2000/pivpn-docker#5]
Running via docker compose:

```yaml
version: "3.7"
services:

  openvpn:
    image: archef2000/pivpn:latest
    container_name: pivpn
    hostname: pivpn
    ports:
      - 21337:21337/udp
    volumes:
      - ./openvpn/ovpns:/home/pivpn/ovpns
      - ./openvpn/etc/openvpn:/etc/openvpn
      - ./openvpn/etc/pivpn/openvpn:/etc/pivpn/openvpn
    environment:
      - HOST=<domain>
      - PROTO=udp # or tcp
      - VPN=openvpn
      - PORT=21337
# optional
      # - CLIENT_NAME=pivpn
      # - NET=10.8.0.0
      # - TWO_POINT_FOUR=1 # or 0 If TWO_POINT_FOUR=0 then ENCRYPT needs to be 2048, 3072, or 4096
      - DNS1=1.1.1.1 # Client DNS
      - DNS2=8.8.8.8 # Client DNS
      # - ENCRYPT=256 # 256, 384, or 521 if TWO_POINT_FOUR=0 then ENCRYPT needs to be 2048, 3072, or 4096
    privileged: true # Is needed to run Openvpn
    restart: always
``` 

log:

```
pivpn  | ::: installing PIVPN
pivpn  | curl: (35) OpenSSL/3.0.9: error:0A000460:SSL routines::reason(1120)
pivpn  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn  | chmod: cannot access '/etc/pivpn/install.sh': No such file or directory
pivpn  | ::: Using the udp protocol
pivpn  | ::: Using port 21337
pivpn  | ::: Using DNS 1.1.1.1 8.8.8.8
pivpn  | ::: Using domain name <domain>
pivpn  | ::: Using VPN NET 10.8.0.0/24
pivpn  | ::: Using openvpn Server
pivpn  | ::: Using a 256-bit certificate
pivpn  | ::: Using OpenVPN 2.4 features
pivpn  | ::: Installation Complete!
pivpn  | ::: PiVPN Service Started
pivpn exited with code 0
```

What could be the error here?

**Comment by redlegoman** [comment]
This seems to be because sh/reconf does not download the pivpn install.sh. I replaced the line
`curl -fsSL0 https://install.pivpn.io -o "${INSTALLER}"
`
with
`curl -fsSL https://install.pivpn.io`
and rebuilt the image and it seems to work

**Comment by redlegoman** [comment]
created pull request https://github.com/archef2000/pivpn-docker/pull/6

**Comment by cwong-archy** [comment]
> created pull request #6

hey @redlegoman, i followed your instruction and built an image. the startup shows no error but i think its not doing anything.
```
──── docker compose -f ~/raspberry-pi/docker/wireguard/docker-compose.yml up
[+] Running 1/1
 ✔ Container pivpn  Recreated
Attaching to pivpn
pivpn  | ::: Container Started
pivpn  | ::: Pre Config of PIVPN.
pivpn  | ::: installing PIVPN
pivpn  | ::: Using the udp protocol
pivpn  | ::: Using port 51820
pivpn  | ::: Using DNS 8.8.8.8 8.8.4.4
pivpn  | ::: Using domain name my-pivpn-address.duckdns.org
pivpn  | ::: Using VPN NET 10.8.0.0/24
pivpn  | ::: Using wireguard Server

pivpn  | ::: Installation Complete!
pivpn  | ::: PiVPN Service Started
pivpn exited with code 0
```

i `exec`'ed into the container but thereis no `pivpn` command. i am not sure what to do at this point. please advice. thanks.

docker-compose.yml is pretty straight forward at this point. i have the `INTERFACE=wlan0`, not sure if thats correct, wlan0 is my outbound device to the house router -
```
---
version: '3'
services:
  wireguard:
    image: localbuildimage/pivpn:latest
    container_name: pivpn
    hostname: pivpn
    ports:
      - 51820:51820/udp
    volumes:
      - ./home-pivpn-configs:/home/pivpn/configs
      - ./etc-wireguard:/etc/wireguard
    environment:
      - VPN=wireguard
      - HOST=my-pivpn-address.duckdns.org
      - PORT=51820
      - INTERFACE=wlan0
      # optional
      # - CLIENT_NAME=pivpn
      # - NET=10.8.0.0
      # - DNS1=1.1.1.1 # Client DNS
      # - DNS2=9.9.9.9 # Client DNS
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
```

UPDATE -

after a while the log showed this -
```
pivpn  | ::: Installation Complete!
pivpn  | ::: PiVPN Service Started
pivpn exited with code 0
```

**Comment by redlegoman** [comment]
no idea. Looks like you're using wireguard - I am not, I would guess at something in your config or docker-compose.yml file.

**Comment by alexsalex** [comment]
Same issue:
```
pivpn-ov  | ::: Container Started
pivpn-ov  | ::: Pre Config of PIVPN.
pivpn-ov  | ::: installing PIVPN
pivpn-ov  | curl: (35) OpenSSL/3.0.11: error:0A000460:SSL routines::reason(1120)
pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
pivpn-ov  | chmod: cannot access '/etc/pivpn/install.sh': No such file or directory
pivpn-ov  | ::: Using the udp protocol
pivpn-ov  | ::: Using port 1194
pivpn-ov  | ::: Using DNS 1.1.1.1 9.9.9.9
pivpn-ov  | ::: Using domain name vpn.duck.go
pivpn-ov  | ::: Using VPN NET 10.12.0.0/24
pivpn-ov  | ::: Using openvpn Server
pivpn-ov  | ::: Using a 256-bit certificate
pivpn-ov  | ::: Using OpenVPN 2.4 features
pivpn-ov  | ::: Installation Complete!
pivpn-ov  | ::: PiVPN Service Started
pivpn-ov exited with code 0
```

**Comment by cwong-archy** [comment]
> Same issue:
> 
> ```
> pivpn-ov  | ::: Container Started
> pivpn-ov  | ::: Pre Config of PIVPN.
> pivpn-ov  | ::: installing PIVPN
> pivpn-ov  | curl: (35) OpenSSL/3.0.11: error:0A000460:SSL routines::reason(1120)
> pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
> pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
> pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
> pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
> pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
> pivpn-ov  | sed: can't read /etc/pivpn/install.sh: No such file or directory
> pivpn-ov  | chmod: cannot access '/etc/pivpn/install.sh': No such file or directory
> pivpn-ov  | ::: Using the udp protocol
> pivpn-ov  | ::: Using port 1194
> pivpn-ov  | ::: Using DNS 1.1.1.1 9.9.9.9
> pivpn-ov  | ::: Using domain name vpn.duck.go
> pivpn-ov  | ::: Using VPN NET 10.12.0.0/24
> pivpn-ov  | ::: Using openvpn Server
> pivpn-ov  | ::: Using a 256-bit certificate
> pivpn-ov  | ::: Using OpenVPN 2.4 features
> pivpn-ov  | ::: Installation Complete!
> pivpn-ov  | ::: PiVPN Service Started
> pivpn-ov exited with code 0
> ```

hey @alexsalex, so i simply just went with wireguard and not using pivpn.
this link helped me - https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole

you can just hit `http://{pi.local}:51821/` to manage user.

```
---
version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      wireguard:
        ipv4_address: 10.8.1.53
...
  wireguard:
    container_name: wireguard
    image: weejewel/wg-easy:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      WG_HOST: mysubdomain.duckdns.org
      PASSWORD: password-to-login-to-UI
      WG_DEFAULT_DNS: 10.8.1.53
    networks:
      wireguard:
        ipv4_address: 10.8.1.2
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - './wireguard/etc-wireguard:/etc/wireguard'
networks:
  wireguard:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```
